"""testing remove task id from approval table

Revision ID: c496214b3a08
Revises: e4d5ccbdd63f
Create Date: 2026-07-20 19:36:46.933558

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c496214b3a08'
down_revision: Union[str, Sequence[str], None] = 'e4d5ccbdd63f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('approvals_task_id_key'), 'approvals', type_='unique')
    op.drop_column('approvals', 'task_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('approvals', sa.Column('task_id', sa.VARCHAR(length=64), autoincrement=False, nullable=False))
    op.create_unique_constraint(op.f('approvals_task_id_key'), 'approvals', ['task_id'], postgresql_nulls_not_distinct=False)
    # ### end Alembic commands ###
